### ISSUE TITLE
failing specs under ng-pipeline

### ISSUE THREAD

**Issue by colinsurprenant** [logstash-plugins/logstash-output-file#25]
This spec fail is intermittent and I cannot reproduce it systematically. I have to run the specs a few times to trigger it. @andrewvc this error seems to indicate out-or-order batches since the `Expected 6249, but got 6374` difference is exactly 125, the default batch size.

```
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
F...................

Failures:

  1) LogStash::Outputs::File ship lots of events to a file agent(/Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-output-file/spec/outputs/file_spec.rb:31:in) runs
     Failure/Error: block.call
     Insist::Failure:
       Expected 6249, but got 6374
     # ./vendor/bundle/jruby/1.9/gems/insist-1.0.0/lib/insist/assert.rb:8:in `assert'
     # ./vendor/bundle/jruby/1.9/gems/insist-1.0.0/lib/insist/comparators.rb:14:in `=='
     # /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-output-file/spec/outputs/file_spec.rb:38:in `(root)'
     # /Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-output-file/spec/outputs/file_spec.rb:35:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/logstash-devutils-0.0.18-java/lib/logstash/devutils/rspec/logstash_helpers.rb:107:in `agent'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'
     # ./lib/bootstrap/rspec.rb:11:in `(root)'

Finished in 3.11 seconds (files took 0.916 seconds to load)
20 examples, 1 failure

Failed examples:

rspec ./vendor/bundle/jruby/1.9/gems/logstash-devutils-0.0.18-java/lib/logstash/devutils/rspec/logstash_helpers.rb:104 # LogStash::Outputs::File ship lots of events to a file agent(/Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-output-file/spec/outputs/file_spec.rb:31:in) runs

Randomized with seed 49502
```

**Comment by andrewvc** [comment]
Fixed in #26
