### ISSUE TITLE
Windows test failure

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-output-file#5]
From https://github.com/elasticsearch/logstash/issues/2487

```
  50) LogStash::Outputs::File#register doesnt allow the root directory to have some dynamic part
     Failure/Error: expect { output.register }.to raise_error(LogStash::ConfigurationError)
       expected LogStash::ConfigurationError but nothing was raised
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  51) LogStash::Outputs::File#register doesnt allow the path to start with a dynamic string
     Failure/Error: expect { output.register }.to raise_error(LogStash::ConfigurationError)
       expected LogStash::ConfigurationError but nothing was raised
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  52) LogStash::Outputs::File receiving events when using an interpolated path when trying to write outside the files root directory doesnt decode relatives paths urlencoded
     Failure/Error: Stud::Temporary.directory('filepath_error') do |path|
     Errno::EACCES:
       Permission denied - C:\Users\jls\AppData\Local\Temp/filepath_error-adf927dc3ebc4a0fb84cafe97f65a2eec1058c8f3c8b19e2df4d41cce019/%252E%252E%252F%252E%252E%252Ftest
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  53) LogStash::Outputs::File receiving events when using an interpolated path when trying to write outside the files root directory doesnt write outside the file if the path is double escaped
     Failure/Error: Stud::Temporary.directory('filepath_error') do |path|
     Errno::EACCES:
       Permission denied - C:\Users\jls\AppData\Local\Temp/filepath_error-b60b51f99dcaaa2826a1a47b63b375e8f74c80169261df7b6ca1926872e8/_filepath_failures
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  54) LogStash::Outputs::File receiving events when using an interpolated path when trying to write outside the files root directory writes the bad event in the specified error file
     Failure/Error: Stud::Temporary.directory('filepath_error') do |path|
     Errno::EACCES:
       Permission denied - C:\Users\jls\AppData\Local\Temp/filepath_error-42480b44ede029844ef71d23dbef79ede0dfab29de4787200beffd4f799f/_error
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  55) LogStash::Outputs::File receiving events when using an interpolated path when trying to write inside the file root directory write the events to the generated path containing multiples fieldref
     Failure/Error: Stud::Temporary.directory do |path|
     Errno::EACCES:
       Permission denied - C:\Users\jls\AppData\Local\Temp/studtmp-0e1f0472fac607d455778d85ad8155a40c23d795db762d7a5a22f7ffa716/42/critical/deep/nested/failed_syslog-2015-01-30
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  56) LogStash::Outputs::File receiving events when using an interpolated path when trying to write inside the file root directory write the event to the generated filename with multiple deep
     Failure/Error: Stud::Temporary.directory do |path|
     Errno::EACCES:
       Permission denied - C:\Users\jls\AppData\Local\Temp/studtmp-1d6d668d5b4ae0b031a8d577c4685e87693132219bd9d4844945bc8b5d2f/inside/errors/42.txt
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  57) LogStash::Outputs::File receiving events when using an interpolated path when trying to write inside the file root directory write the events to a file when some part of a folder or file is dynamic
     Failure/Error: Stud::Temporary.directory do |path|
     Errno::EACCES:
       Permission denied - C:\Users\jls\AppData\Local\Temp/studtmp-82a8746a73798552c04757efea83fbbf847bb04f3f58e92fdbded7b42a21/failed_syslog-2015-01-30
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  58) LogStash::Outputs::File receiving events when using an interpolated path when trying to write inside the file root directory write the event to the generated filename
     Failure/Error: Stud::Temporary.directory do |path|
     Errno::EACCES:
       Permission denied - C:\Users\jls\AppData\Local\Temp/studtmp-56b5e97a4e9dd311217a000e489dad5922ca8f603761db0ca0c428aec36e/42.txt
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  59) LogStash::Outputs::File ship lots of events to a file gzipped agent(C:/Users/jls/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-file-0.1.3/spec/outputs/file_spec.rb:65:in) runs
     Failure/Error: pipeline = LogStash::Pipeline.new(config)
     LogStash::PluginLoadingError:
       Couldn't find any input plugin named 'generator'. Are you sure this is correct? Trying to load the generator input plugin resulted in this error: no such file to load -- logstash/inputs/generator
     # ./lib/logstash/plugin.rb:142:in `lookup'
     # ./lib/logstash/plugin.rb:140:in `lookup'
     # ./lib/logstash/pipeline.rb:270:in `plugin'
     # (eval):7:in `initialize'
     # ./lib/logstash/pipeline.rb:32:in `initialize'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'

  60) LogStash::Outputs::File ship lots of events to a file agent(C:/Users/jls/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-file-0.1.3/spec/outputs/file_spec.rb:30:in) runs
     Failure/Error: pipeline = LogStash::Pipeline.new(config)
     LogStash::PluginLoadingError:
       Couldn't find any input plugin named 'generator'. Are you sure this is correct? Trying to load the generator input plugin resulted in this error: no such file to load -- logstash/inputs/generator
     # ./lib/logstash/plugin.rb:142:in `lookup'
     # ./lib/logstash/plugin.rb:140:in `lookup'
     # ./lib/logstash/pipeline.rb:270:in `plugin'
     # (eval):7:in `initialize'
     # ./lib/logstash/pipeline.rb:32:in `initialize'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'
```

**Comment by ph** [comment]
https://github.com/logstash-plugins/logstash-output-file/pull/6
